version: '3.3'
# todo
# 1. 이름 바꿀것
# 2. jenkins에 docker hub, github credentials 추가
services:
  front:
    container_name: front
    image: taehopark/myname-front
    build:
      context: frontend
      dockerfile: Dockerfile
    restart: always
    command : npm start
    ports:
      - "3000:3000"
    networks:
      - jenkins-network

  back:
    container_name: back
    image: taehopark/myname-back
    build:
      context: backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8081:8081"
    networks:
      - jenkins-network

networks:
  jenkins-network:
    external: true
