version: '3.3'

services:
  database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: mysql
      MYSQL_ROOT_PASSWORD: 9546
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql

  front:
    container_name: front
    image: taehopark/myname-front
    build:
      context: frontend
      dockerfile: Dockerfile
    restart: always
    command : npm start
    ports:
      - "3000:3000"
    networks:
      - jenkins-network

  back:
    container_name: back
    image: taehopark/myname-back
    build:
      context: backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8081:8081"
    networks:
      - jenkins-network

networks:
  jenkins-network:
    external: true

volumes:
  mysql: