version: '3.3'
# todo
# 1. 이름 바꿀것
# 2. jenkins에 docker hub, github credentials 추가
services:
#  certbot:
#    container_name: certbot
#    image: certbot/certbot
#    restart: unless-stopped
#    volumes:
#      - ./certbot/conf:/etc/letsencrypt:rw
#      - ./certbot/www:/var/www/certbot:rw
#    #    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
#    depends_on:
#      - nginx


  nginx:
    container_name: nginx
    image: taehopark/myname-nginx
    build:
      context: nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - jenkins-network
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt
    depends_on:
      - back

  front:
    container_name: front
    image: taehopark/myname-front
    build:
      context: frontend
      dockerfile: Dockerfile
    restart: always
    command : npm start
    ports:
      - "3000:3000"
    networks:
      - jenkins-network

  back:
    container_name: back
    image: taehopark/myname-back
    build:
      context: backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8081:8081"
    networks:
      - jenkins-network
# 환경변수 지정


  redis:
    container_name: redis
    hostname: redis
    image: redis:alpine
    restart: unless-stopped
    networks:
      - jenkins-network
    volumes:
      - ~/redis/data:/data
    user: redis
#    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"

networks:
  jenkins-network:
    external: true
