version: '3.8'
# todo
# 1. 이름 바꿀것
# 2. jenkins에 docker hub, github credentials 추가
services:
#  nginx:
#    container_name: nginx
#    image: taehopark/myname-nginx
#    build:
#      context: nginx
#      dockerfile: Dockerfile
#    restart: unless-stopped
#    ports:
#      - "81:81"
#    networks:
#      - jenkins-network
#    depends_on:
#      - back

  front:
    container_name: front
    image: taehopark/myname-front
    build:
      context: frontend
      dockerfile: Dockerfile
    restart: always
    command : npm start
    ports:
      - "3000:3000"
    networks:
      - jenkins-network

  back:
    container_name: back
    image: taehopark/myname-back
    build:
      context: backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8081:8081"
    networks:
      - jenkins-network
# 환경변수 지정


  redis:
    container_name: redis
    hostname: redis
    image: redis:alpine
    restart: unless-stopped
    networks:
      - jenkins-network
    volumes:
      - ~/redis/data:/data
    user: redis
#    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"

networks:
  jenkins-network:
    external: true
