version: '3.3'

services:

  front:
    container_name: front
    image: taehopark/myname-front
    build:
      context: frontend
      dockerfile: Dockerfile
    restart: always
    command : npm start
    ports:
      - "3000:3000"
    networks:
      - jenkins-network

  back:
    container_name: back
    image: taehopark/myname-back
    build:
      context: backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8081:8081"
    networks:
      - jenkins-network

  nginx:
    container_name: nginx
    image: taehopark/myname-nginx
    build:
      context: nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
      - "4443:443"
    networks:
      - jenkins-network
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt
    depends_on:
      - back

networks:
  jenkins-network:
    external: true
